-- GENERATED by C->Haskell Compiler, version 0.27.1 Eternal Sunshine, 29 November 2015 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "/Users/ocramz/Dropbox/RESEARCH/Haskell/petsc-hs/src/Numerical/PETSc/Internal/Types.chs" #-}
{-# LANGUAGE ForeignFunctionInterface #-}
module Numerical.PETSc.Internal.Types
--        (
--   PetscInt,
--   PetscScalar,
--   PetscBool,
--   PetscReal,
-- --  ErrCodeA                      
--              )
       where
import qualified Foreign.C.Types as C2HSImp



import Foreign
import Foreign.C.Types
import Foreign.Storable



type PetscInt_ = (C2HSImp.CInt)
{-# LINE 18 "/Users/ocramz/Dropbox/RESEARCH/Haskell/petsc-hs/src/Numerical/PETSc/Internal/Types.chs" #-}

type PetscScalar_ = (C2HSImp.CDouble)
{-# LINE 19 "/Users/ocramz/Dropbox/RESEARCH/Haskell/petsc-hs/src/Numerical/PETSc/Internal/Types.chs" #-}

type PetscReal_ = (C2HSImp.CDouble)
{-# LINE 20 "/Users/ocramz/Dropbox/RESEARCH/Haskell/petsc-hs/src/Numerical/PETSc/Internal/Types.chs" #-}

-- /* typedef enum { PETSC_FALSE,PETSC_TRUE } PetscBool; */
-- {#enum PetscBool as PetscBool {underscoreToCase} deriving (Eq, Show)#}
type PetscBool_ = (C2HSImp.CInt)
{-# LINE 23 "/Users/ocramz/Dropbox/RESEARCH/Haskell/petsc-hs/src/Numerical/PETSc/Internal/Types.chs" #-}

-- deriving instance Storable PetscBool

-- * IS





-- * Vec




-- * Mat






-- * DM




-- -- * DMDA






-- * KSP




-- * PF




-- * SNES




-- * TS





-- * TAO




-- * Viewer




-- * PETSc misc




-- * MPI misc



-- CString




-- errors etc


-- /* typedef int PetscErrorCode; */
-- {#typedef PetscErrorCode CInt#}
-- {#default out `ErrCode' [PetscErrorCode] convErrCode#}
-- convErrCode :: CInt -> ErrCode
-- convErrCode = ErrCode . fromIntegral
-- newtype ErrCode = ErrCode { unErrCode :: Int } deriving (Eq, Show)




