sudo: 
  false

# # # A lightweight base image (C); we provide our own build tools.

language: 
  c 

services:
  - docker
  
# # # The different configurations we want to test. You could also do things like
# # # change flags or use --stack-yaml to point to a different file.

env:
  # - STACK_ARGS="" PETSC_VERSION=3.6.2 SLEPC_VERSION=3.6.1
  # - STACK_ARGS="" PETSC_VERSION=3.7.2 SLEPC_VERSION=3.7.1
  # - STACK_ARGS="--resolver lts-2"
  # - STACK_ARGS="--resolver lts-3"
  # - STACK_ARGS="--resolver lts"
  # - STACK_ARGS="--resolver nightly"

# addons:
#   apt:
#     packages:
#     - gfortran            # needed to build PETSc
#     - libgmp-dev          # needed by GHC




before_install:


script:
  # - make docker_build
  # - docker build -t ocramz/petsc-hs .
  
  - make docker_upd
  # - docker run --rm -it ocramz/petsc-hs update-petsc-hs.sh

  - docker images




# cache:
#   directories:
#   - $PETSC_DIR
#   - $SLEPC_DIR
# #   - $HOME/.stack


