flags: {}
packages:
- '.'
extra-deps: 
- inline-c-0.5.5.1
# # resolver: lts-1.0 # corresponds to ghc-7.8.4
# resolver: lts-5.15 # corresponds to ghc-7.10.3



# extra-include-dirs:
# - /usr/local/opt/icu4c/include
# extra-lib-dirs:
# - /usr/local/opt/icu4c/lib

#   # include-dirs:        /Users/ocramz/petsc-3.6.2/include, /Users/ocramz/petsc-3.6.2/arch-darwin-c-debug/include
#   # extra-lib-dirs:      lib, /Users/ocramz/petsc-3.6.2/arch-darwin-c-debug/lib, /Users/ocramz/petsc-3.6.2/arch-darwin-c-debug/lib/pkgconfig