flags: {}
packages:
- '.'
extra-deps: 
- inline-c-0.5.5.3
# resolver: lts-1.0            # ghc-7.8.4
# resolver: lts-5.15           # ghc-7.10.3
resolver: nightly-2016-06-20 # ghc 8.0.1
ghc-options:
  "*": -fno-warn-missing-signatures -fno-warn-unused-do-bind -fno-warn-unused-imports