flags: {}
packages:
- '.'
extra-deps: 
- inline-c-0.5.5.1
# # resolver: lts-1.0 # corresponds to ghc-7.8.4
# # resolver: lts-5.15 # corresponds to ghc-7.10.3
resolver: nightly-2016-06-11
ghc-options:
  "*": -fno-warn-missing-signatures -fno-warn-unused-do-bind -fno-warn-unused-imports