-- GENERATED by C->Haskell Compiler, version 0.27.1 Eternal Sunshine, 29 November 2015 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "/Users/ocramz/Dropbox/RESEARCH/Haskell/petsc-hs/src/Numerical/PETSc/Internal/C2HsGen/TypesC2HsGen.chs" #-}
{-# LANGUAGE ForeignFunctionInterface#-}

module Numerical.PETSc.Internal.C2HsGen.TypesC2HsGen where
import qualified Foreign.C.Types as C2HSImp


import Numerical.PETSc.Internal.Utils
import Foreign
import Foreign.Storable













data DMBoundaryType_ = DmBoundaryNone
                     | DmBoundaryGhosted
                     | DmBoundaryMirror
                     | DmBoundaryPeriodic
                     | DmBoundaryTwist
  deriving (Enum,Eq,Show)

{-# LINE 20 "/Users/ocramz/Dropbox/RESEARCH/Haskell/petsc-hs/src/Numerical/PETSc/Internal/C2HsGen/TypesC2HsGen.chs" #-}

type DMBoundaryType = (C2HSImp.CInt)
{-# LINE 21 "/Users/ocramz/Dropbox/RESEARCH/Haskell/petsc-hs/src/Numerical/PETSc/Internal/C2HsGen/TypesC2HsGen.chs" #-}

dmBoundaryTypeToC x = (toCInt $ fromEnum   x  ::  DMBoundaryType_) :: DMBoundaryType
dmBoundaryTypeFromC c = (toEnum $ fromIntegral   c  ::  DMBoundaryType) :: DMBoundaryType_

