-- GENERATED by C->Haskell Compiler, version 0.25.2 Snowboundest, 31 Oct 2014 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "/Users/ocramz/Dropbox/TUD200624/Haskell/petsc-hs-inline-c/src/Numerical/PETSc/Types.chs" #-}
{-# LANGUAGE ForeignFunctionInterface #-}
module Numerical.PETSc.Types
--        (
--   PetscInt,
--   PetscScalar,
--   PetscBool,
--   PetscReal,
-- --  ErrCodeA                      
--              )
       where

import Foreign
import Foreign.C.Types
import Foreign.Storable



type PetscInt_ = (CInt)
{-# LINE 18 "/Users/ocramz/Dropbox/TUD200624/Haskell/petsc-hs-inline-c/src/Numerical/PETSc/Types.chs" #-}

type PetscScalar_ = (CDouble)
{-# LINE 19 "/Users/ocramz/Dropbox/TUD200624/Haskell/petsc-hs-inline-c/src/Numerical/PETSc/Types.chs" #-}

type PetscReal_ = (CDouble)
{-# LINE 20 "/Users/ocramz/Dropbox/TUD200624/Haskell/petsc-hs-inline-c/src/Numerical/PETSc/Types.chs" #-}

-- /* typedef enum { PETSC_FALSE,PETSC_TRUE } PetscBool; */
-- {#enum PetscBool as PetscBool {underscoreToCase} deriving (Eq, Show)#}
type PetscBool_ = (CInt)
{-# LINE 23 "/Users/ocramz/Dropbox/TUD200624/Haskell/petsc-hs-inline-c/src/Numerical/PETSc/Types.chs" #-}

-- deriving instance Storable PetscBool

-- * IS





-- * Vec




-- * Mat






-- * DM




-- -- * DMDA






-- * KSP




-- * PF




-- * SNES




-- * TS





-- * TAO




-- * Viewer




-- * PETSc misc




-- * MPI misc



-- CString




-- errors etc


-- /* typedef int PetscErrorCode; */
-- {#typedef PetscErrorCode CInt#}
-- {#default out `ErrCode' [PetscErrorCode] convErrCode#}
-- convErrCode :: CInt -> ErrCode
-- convErrCode = ErrCode . fromIntegral
-- newtype ErrCode = ErrCode { unErrCode :: Int } deriving (Eq, Show)


-- -- KSP


